### ISSUE TITLE
Side menu doesn't retain state

### ISSUE THREAD

**Issue by sanath1599** [coding-Studio-vbit/cswebsite#103]
The side menu in the Editorials doesn't retain a collapsed or expanded state. It keeps returning to expanded state even after resolving.

**Comment by akshayrajp** [comment]
@Aaris03Khan Take up this issue please

**Comment by Aaris03Khan** [comment]
Alright @akshayrajp

**Comment by sanath1599** [comment]
> Alright @akshayrajp

I think this is fixed in #102 please check and update me if it's right!

**Comment by Aaris03Khan** [comment]
Hello @sanath1599 @akshayrajp,
The side menu has been fixed in #103 update.
