### ISSUE TITLE
Issue with the responsiveness of the "hall of fame" page

### ISSUE THREAD

**Issue by eyeamkd** [coding-Studio-vbit/cswebsite#36]
-> Please make the title and the content appear in a vertical direction 
-> Reduce the size of image and follow the same layout as above 

![Screenshot 2020-03-27 at 8 28 18 PM](https://user-images.githubusercontent.com/31094327/77769373-be9c1b00-7069-11ea-8991-41b34aee15a0.png)

![Screenshot 2020-03-27 at 8 28 06 PM](https://user-images.githubusercontent.com/31094327/77769240-914f6d00-7069-11ea-91e9-b003cabb2910.png)

**Comment by yasaswiraj** [comment]
alright! I will be working on it.

**Comment by Saravanan-Jodavula** [comment]
@yasaswiraj cool, I assigned the issue to you.

**Comment by Saravanan-Jodavula** [comment]
@yasaswiraj good job on solving the issue.
