### ISSUE TITLE
Mail Icon and Youtube link 

### ISSUE THREAD

**Issue by eyeamkd** [coding-Studio-vbit/cswebsite#37]
- The Mail ( Gmail ) icon present in the bottom of the home page, redirects to gmail.com, which doesn't make any sense 
- Add youtube channel link too there

**Comment by Vishnu-19** [comment]
I'll take this up

**Comment by abhiram2600** [comment]
I want to take this up. But, why is there gmail in follow us?. And is coding studio VBIT  our YouTube channel?

**Comment by Saravanan-Jodavula** [comment]
good job @Vishnu-19 !!
