### ISSUE TITLE
Forum Members' Display Pictures

### ISSUE THREAD

**Issue by eyeamkd** [coding-Studio-vbit/cswebsite#39]
Please add the DPs of the forum members

**Comment by eyeamkd** [comment]
@bsaikiran618 assign this issue to any SDE-II

**Comment by eyeamkd** [comment]
Since @bsaikiran618 hasn't assigned this issue to anyone, I'm assigning this to @ramugoud

**Comment by Saravanan-Jodavula** [comment]
Since @ramugoud is in quarantine, I'm assigning this issue to @Anishahaha
