### ISSUE TITLE
Remove the previous tenure from about

### ISSUE THREAD

**Issue by eyeamkd** [coding-Studio-vbit/cswebsite#40]
- Please, remove the previous tenure from about, only the current tenure info stays 
- Please add GB, under current tenure

**Comment by Saravanan-Jodavula** [comment]
@yasaswiraj can u take this up??

**Comment by eyeamkd** [comment]
Since nobody has voluntarily taken this up, I've assigned @Aaris03Khan to resolve this issue. 
I hope that's okay.

**Comment by Saravanan-Jodavula** [comment]
@eyeamkd I'm closing this issue since it has been solved
