### ISSUE TITLE
Images and More details about previously conducted events

### ISSUE THREAD

**Issue by eyeamkd** [coding-Studio-vbit/cswebsite#41]
- Add Images of CodeCraft 1 and CSSOC 
- Also add CodeCraft Beta under second tenure events 
- it'd be better if the events are categorized by years rather than tenure ( just a suggestion)

**Comment by eyeamkd** [comment]
@themohan @msaichaitanya735 @Saravanan-Jodavula  @akshayrajp  
awaiting confirmation from your end

**Comment by akshayrajp** [comment]
@themohan and @msaichaitanya735 please take up the first issue (pictures one).

**Comment by eyeamkd** [comment]
Update on this ?

**Comment by themohan** [comment]
yes @eyeamkd gathering images

**Comment by Saravanan-Jodavula** [comment]
@themohan @msaichaitanya735 @akshayrajp status?

**Comment by akshayrajp** [comment]
@eyeamkd 

> Also add CodeCraft Beta under second tenure events

Done

> it'd be better if the events are categorized by years rather than tenure ( just a suggestion)

Done


@themohan waiting for images

**Comment by themohan** [comment]
@akshayrajp  i didn't find any new images, so i mailed sanath for images.

**Comment by akshayrajp** [comment]
@sanath1599 Do you have any good pictures of codeCraft and CSSOC? If you do, please mail them over to @themohan , else close this issue. Thanks!

**Comment by sanath1599** [comment]
> @sanath1599 Do you have any good pictures of codeCraft and CSSOC? If you do, please mail them over to @themohan , else close this issue. Thanks!

Don't have it man.

**Comment by akshayrajp** [comment]
Alright then, that does it. GG.
