### ISSUE TITLE
Logo on landing page has a weird glow on hover.

### ISSUE THREAD

**Issue by akylus** [coding-Studio-vbit/cswebsite#48]
The glow stays for a second or so after moving the pointer away and it fluctuates sometimes

**Comment by Saravanan-Jodavula** [comment]
@akylus it was added purpoesfully. aesthetic bruh.

**Comment by Saravanan-Jodavula** [comment]
@akylus shall I close this issue?

**Comment by akylus** [comment]
looks weird, enhance it atleast.

**Comment by eyeamkd** [comment]
@akylus, if you're not satisfied, assign any SDE3 to this issue else close this issue

**Comment by akylus** [comment]
Fine, closing it
