### ISSUE TITLE
History of cS doesn't have any "history". 

### ISSUE THREAD

**Issue by akylus** [coding-Studio-vbit/cswebsite#49]
Content currently over there can be placed on the main landing page, giving a gist of what cS is.

**Comment by eyeamkd** [comment]
@akylus assign any SDE3 to this issue

**Comment by akylus** [comment]
@Saravanan-Jodavula please look into this. Ask @akshayrajp to write some history in the history box.

**Comment by Saravanan-Jodavula** [comment]
@akshayrajp please write some content for history box.

**Comment by akshayrajp** [comment]
On it

**Comment by akshayrajp** [comment]
Waiting on @eyeamkd to give the history part.

**Comment by eyeamkd** [comment]
@akylus informed me just a while ago, I'll send it over by tomorrow night

**Comment by akylus** [comment]
@akshayrajp please check I've given you the content

**Comment by akshayrajp** [comment]
Fixed here : https://github.com/coding-Studio-vbit/cswebsite/pull/102
