### ISSUE TITLE
SEO Issues

### ISSUE THREAD

**Issue by sanath1599** [coding-Studio-vbit/cswebsite#65]
meta description of cc.html too long,
suggested length: 50 - 160 characters
found length: 216 characters,
this will result in over 50 charecters not being indexed by Google, use https://commentpicker.com/character-counter.php to check if you want

> Meta out of limit for cc.html, gallery.html, cssoc/cc.html,cssoc/gallery.html
> please rename cc to codecraft.html and cssoc.html, these pages will get indexed in google and if you change it later will cause 404 errors resulting in downgrade of the rank in future. so better to change it now itself

**Comment by Saravanan-Jodavula** [comment]
@bsaikiran618 let's do these off now

**Comment by bsaikiran618** [comment]
On it

**Comment by bsaikiran618** [comment]
Done
