### ISSUE TITLE
Massive Issues list for future address

### ISSUE THREAD

**Issue by sanath1599** [coding-Studio-vbit/cswebsite#66]
# Pending Issues
2) contact form doesn't work
4) does newsletter option work in contact us page?

# Solved Issues
> 1)why does editorial have aaris number and contact us have @dR.mAnhattan#7926  number?
> 3) consider redirecting the github icon in contact us to the cS organization page and not the website repo
> 5) too many dummy links in the footer of contact page
> 6) every page shows "About us" highlighted in the menu - change active element in css 
> 7) no nav bar for editorial to navigate back to the main website?
> 8) contact page doesn't have "events" in the navbar
> 9) Facebook icon in contact us has no link attached 
> 10) Why only editorials have a favicon? also, consider using white cs logo for favicon

**Comment by akshayrajp** [comment]
1,3,5,8,9

These are the issues that I'll take up

**Comment by akshayrajp** [comment]
An update, 1 has been fixed by @msaichaitanya735 and I'm fixing 3,5,8,9.

The 3rd issue 
> consider redirecting the github icon in contact us to the cS organization page and not the website repo

may have already been fixed since it does redirect to [](https://github.com/coding-Studio-vbit/)

**Comment by akshayrajp** [comment]
Fixed 5th issue:

> too many dummy links in the footer of contact page

Fixed 9th issue:

> Facebook icon in contact us has no link attached

The 8th issue

> contact page doesn't have "events" in the navbar

..is not exactly an issue since we removed the "events" section from the navbar long ago

**Comment by akshayrajp** [comment]
> no nav bar for editorial to navigate back to the main website?

@sanath1599 By editorial, do you mean the editorial landing page or the multiple pages where the solutions to the questions are explained?

**Comment by sanath1599** [comment]
> > no nav bar for editorial to navigate back to the main website?
> 
> @sanath1599 By editorial, do you mean the editorial landing page or the multiple pages where the solutions to the questions are explained?

The pages where solutions are explained. There should be a way to navigate back to the main website.

**Comment by akshayrajp** [comment]
> > > no nav bar for editorial to navigate back to the main website?
> > 
> > @sanath1599 By editorial, do you mean the editorial landing page or the multiple pages where the solutions to the questions are explained?
> 
> The pages where solutions are explained. There should be a way to navigate back to the main website. 

Alright Sanath, will fix it myself or will assign someone to do the job.

**Comment by akshayrajp** [comment]
@Aaris03Khan Take up this issue. Add navbar to every editorial page.

**Comment by akshayrajp** [comment]
Fixed 1st issue

> 1)why does editorial have aaris number and contact us have @dR.mAnhattan#7926 number?
.. by making necessary changes to the said pages.

Fixed 6th issue

> 6) every page shows "About us" highlighted in the menu - change active element in css

.. by adding the active element to pages where it belongs. Note that some pages will have 'About' as their active element, because there are a part of the 'About' section of coding.Studio( );

Fixed 10th issue

> 10) Why only editorials have a favicon? also, consider using white cs logo for favicon

.. by adding the white cS( ); logo as the favicon for every HTML file in the repository

All of these, you can check in https://github.com/coding-Studio-vbit/cswebsite/pull/95

**Comment by akshayrajp** [comment]
@sanath1599 

The 2nd issue 

> contact form doesn't work

and the 3rd issue 

> does newsletter option work in contact us page?

can work only after the website has been hosted on our server, since these are features that can be implemented only on the back-end. @themohan will take care of the implementation part.

As for the newsletter option, yes, it will work, and we plan on sending a curated list of interesting articles once every month, so as to not spam their inbox.

**Comment by sanath1599** [comment]
> @sanath1599 
> 
> The 2nd issue 
> 
> > contact form doesn't work
> 
> and the 3rd issue 
> 
> > does newsletter option work in contact us page?
> 
> can work only after the website has been hosted on our server, since these are features that can be implemented only on the back-end. @themohan will take care of the implementation part.
> 
> As for the newsletter option, yes, it will work, and we plan on sending a curated list of interesting articles once every month, so as to not spam their inbox.
> 

Please make sure the backed is ready tok before hosting it. Don't want people thinking of it as a bug!

**Comment by akshayrajp** [comment]
> > @sanath1599
> > The 2nd issue
> > > contact form doesn't work
> > 
> > 
> > and the 3rd issue
> > > does newsletter option work in contact us page?
> > 
> > 
> > can work only after the website has been hosted on our server, since these are features that can be implemented only on the back-end. @themohan will take care of the implementation part.
> > As for the newsletter option, yes, it will work, and we plan on sending a curated list of interesting articles once every month, so as to not spam their inbox.
> 
> Please make sure the backed is ready tok before hosting it. Don't want people thinking of it as a bug!

Yeah, sure. 

@themohan will be taking care of it.

**Comment by akshayrajp** [comment]
The 4th issue

> no nav bar for editorial to navigate back to the main website?

@Aaris03Khan  tried to add navbar to the editorial pages, but was unable to do so due to some bootstrap error. He tried to look for fixes, but all in vain.

So to navigate back to the main website, we'll be adding a few buttons, that will take the user to Home, Contact Us etc.

@sanath1599

**Comment by sanath1599** [comment]
> The 4th issue
> 
> > no nav bar for editorial to navigate back to the main website?
> 
> @Aaris03Khan  tried to add navbar to the editorial pages, but was unable to do so due to some bootstrap error. He tried to look for fixes, but all in vain.
> 
> So to navigate back to the main website, we'll be adding a few buttons, that will take the user to Home, Contact Us etc.
> 
> @sanath1599 

You already have a sidebar, add a navigation in that maybe!

**Comment by akshayrajp** [comment]
Alright

**Comment by akshayrajp** [comment]
> > The 4th issue
> > 
> > > no nav bar for editorial to navigate back to the main website?
> > 
> > @Aaris03Khan  tried to add navbar to the editorial pages, but was unable to do so due to some bootstrap error. He tried to look for fixes, but all in vain.
> > 
> > So to navigate back to the main website, we'll be adding a few buttons, that will take the user to Home, Contact Us etc.
> > 
> > @sanath1599 
> 
> You already have a sidebar, add a navigation in that maybe! 

Alright! 

@Aaris03Khan make a note.

**Comment by Aaris03Khan** [comment]
The 4th issue has been resolved @akshayrajp @sanath1599

**Comment by akshayrajp** [comment]
@sanath1599 The 4th issue 

> no nav bar for editorial to navigate back to the main website?

has been addressed in https://github.com/coding-Studio-vbit/cswebsite/pull/102

**Comment by sanath1599** [comment]
> @sanath1599 The 4th issue
> 
> > no nav bar for editorial to navigate back to the main website?
> 
> has been addressed in #102

Good job I've updated the issue

**Comment by akshayrajp** [comment]
The other two issues have been addressed over at the backend by @themohan 

Shall I close this issue?

**Comment by sanath1599** [comment]
> The other two issues have been addressed over at the backend by @themohan
> 
> Shall I close this issue?
> 
> @sanath1599

I would request you to wait till the backend is tested and approved before closing the issue!

**Comment by akshayrajp** [comment]
Okay

**Comment by akshayrajp** [comment]
The backend part is working, thanks to @themohan

**Comment by themohan** [comment]
it's my job @akshayrajp
