### ISSUE TITLE
Different hamburger icon appearing on mobile view in Editorial Page

### ISSUE THREAD

**Issue by akylus** [coding-Studio-vbit/cswebsite#83]

**Comment by akshayrajp** [comment]
Can you please be more specific? I find the same icon on mobile view on all pages. Attach screenshots. @akylus

**Comment by akylus** [comment]
I don't think you checked the right page. Find the screenshots below.

![image](https://user-images.githubusercontent.com/32289455/80281912-16db4100-872c-11ea-9a4a-419e228d9c7c.png)


![image](https://user-images.githubusercontent.com/32289455/80281920-1f337c00-872c-11ea-8a3d-bc94391ba454.png)

**Comment by akshayrajp** [comment]
Alright, @Aaris03Khan will be fixing them

**Comment by akshayrajp** [comment]
@Aaris03Khan Please acknowledge. This issue has been assigned to you since you know the best about the editorial pages.

**Comment by Aaris03Khan** [comment]
@akshayrajp on it.

**Comment by Aaris03Khan** [comment]
Issue #83 fixed :)

**Comment by akshayrajp** [comment]
Fixed in https://github.com/akshayrajp/cswebsite/pull/14 and https://github.com/coding-Studio-vbit/cswebsite/pull/99
