### ISSUE TITLE
coding.Studio(); favicon needs to be added

### ISSUE THREAD

**Issue by akylus** [coding-Studio-vbit/cswebsite#84]

**Comment by Saravanan-Jodavula** [comment]
@shivanitumburu I'm assigning this issue to you

**Comment by akshayrajp** [comment]
On what all pages does this need to be done? @Saravanan-Jodavula

**Comment by akshayrajp** [comment]
Done in https://github.com/coding-Studio-vbit/cswebsite/pull/95
