### ISSUE TITLE
Change "Address" to "Details" or something similar

### ISSUE THREAD

**Issue by akylus** [coding-Studio-vbit/cswebsite#85]
![image](https://user-images.githubusercontent.com/32289455/79989974-1ba2b980-84ce-11ea-92eb-2fdb7af7d69f.png)

**Comment by akshayrajp** [comment]
@akylus How about "Reach Us" or "Get in Touch"?

**Comment by akylus** [comment]
Yep, better!

**Comment by akshayrajp** [comment]
Which one tho lol @akylus

**Comment by akshayrajp** [comment]
Imma change it to "Get in Touch"
