### ISSUE TITLE
Edits in the Team section [Check Description]

### ISSUE THREAD

**Issue by akylus** [coding-Studio-vbit/cswebsite#86]
- "Forum" Executive Spelling
- User icons on hover completely fill the circle with purple. It looks odd. Having a lesser opacity would probably help
- Alignment is messing up for width 760px - 990px
- Kunal's icon appears a bit further from the other 3 of the Governing Body
- Governing Body subsection's user-tags still say **Executive**

**Comment by Saravanan-Jodavula** [comment]
@yasaswiraj can you take up this issue?

**Comment by yasaswiraj** [comment]
done!

**Comment by akshayrajp** [comment]
@yasaswiraj fixed this, and the changes have been merged
