### ISSUE TITLE
Broken links found in multiple places

### ISSUE THREAD

**Issue by akylus** [coding-Studio-vbit/cswebsite#88]
Found in events/codecraft/gallery.html on clicking About

![image](https://user-images.githubusercontent.com/32289455/79991165-94eedc00-84cf-11ea-8719-f0cd0def2cb3.png)

**Comment by akylus** [comment]
Same issue  on clicking "Editorial"
![image](https://user-images.githubusercontent.com/32289455/79991296-c4054d80-84cf-11ea-9e6f-dc05f556d67f.png)

**Comment by akylus** [comment]
Another found on clicking About in https://codingstudio.website/events/cssoc/cssoc.html

![image](https://user-images.githubusercontent.com/32289455/79991448-f31bbf00-84cf-11ea-83d3-c08fc903d29f.png)

**Comment by akylus** [comment]
Kindly check all the anchor tags. Found 2 more in other events' navbar too

**Comment by Saravanan-Jodavula** [comment]
@Vishnu-19 please take up this issue.

**Comment by akshayrajp** [comment]
I believe this issue is being caused by so many forks ages behind in terms of commits.

**Comment by akshayrajp** [comment]
@akylus This issue doesn't exist anymore.. I mean, the links are working fine.
