### ISSUE TITLE
Unnecessary dots in about page.

### ISSUE THREAD

**Issue by Saravanan-Jodavula** [coding-Studio-vbit/cswebsite#97]
There are unnecessary dots below my picture in about us. Please remove them. Also, interchange Ramu and Abhiram's pictures. Abhiram is sde-2 now. Also, Abhiram is named as Ramu. Change that too.
![image](https://user-images.githubusercontent.com/47333094/80285852-6da14480-8745-11ea-85a1-f80ac280b7d1.png)

**Comment by akshayrajp** [comment]
Fixed here : https://github.com/coding-Studio-vbit/cswebsite/pull/98
